import config from "../config/config";

export const VERIFICATION_TYPE = {
  FORGOT_PASSWORD: "forgot_password",
  SIGNUP: "signup",
  LOGIN: "login",
};

export const customError = {
  something_went_wrong: "Something went wrong",
};

export const APP = {
  ANDROID: "android",
  IOS: "ios",
}

export const AUTH_PROVIDER = {
  EMAIL: "email",
  APPLE: "apple",
  GOOGLE: "google"
}

export const LIMIT = 20
export const LIMIT_QUIZ = 10


export const IMAGE_FILE_SIZE = 5;
export type InputFormatType = "text" | "image";

export const INPUT_FORMAT_TEXT: InputFormatType = "text";
export const INPUT_FORMAT_IMAGE: InputFormatType = "image";
export const GROUP_ROLE_ADMIN = 'admin'
export const GROUP_ROLE_MEMBER = 'member'

export const SUBSCRIPTION_PLAN = {
  BASIC: 'basic',
  PREMIUM_MONTHLY: 'premium_monthly',
  PREMIUM_YEARLY: 'premium_yearly',
  PREMIUM_PLUS_MONTHLY: 'premium_plus_monthly',
  PREMIUM_PLUS_YEARLY: 'premium_plus_yearly',
}

export const FREE = 'free'
export const PREMIUM = 'premium'
export const PREMIUM_PLUS = 'premium_plus'

export const BILLING_CYCLE = {
  MONTHLY: 'monthly',
  YEARLY: 'yearly',
} as const;
// Quiz constants
export const QUIZ_TYPE = {
  GROUP: 'group',
  FRIEND: 'friend',
} as const;

export const QUIZ_STATUS = {
  ACTIVE: 'active',
  CLOSED: 'closed',
  PENDING: 'pending',
} as const;

// Friend request constants
export const REQUEST_STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
} as const;

export const REQUEST_ACTION = {
  APPROVE: 'approve',
  REJECT: 'reject',
} as const;

// Tab constants
export const TAB_TYPE = {
  FRIENDS: 'friends',
  GROUPS: 'groups',
  REQUESTS: 'requests',
} as const;

export const MAX_PURPOSE_LENGTH = 200
export const MAX_NO_OF_QUESTIONS = 5
export const MIN_NO_OF_QUESTIONS = 3

export const EMAIL_MAX_LENGTH = 254
export const PASSWORD_MAX_LENGTH = 30
export const NAME_MAX_LENGTH = 100
export const OTP_LENGTH = 4
export const OTP_TIMER_SECONDS = 60
export const FRIEND_NAME_TRUNCATE_LENGTH = 6
export const NAME_TRUNCATION_SUFFIX = "..."

export const TIMELINE_PAGE_LIMIT = 10
export const TIMELINE_SCROLL_THRESHOLD = 100

export const SPEAK_TO_TEXT_RESTART_DELAY = 700
export const SPEAK_TO_TEXT_LANGUAGE = "en-US"
export const TOAST_DEFAULT_DURATION = 3000

export const ANALYSER_TEXT = "text";
export const ANALYSER_PORTRAIT = "portrait";

export const APP_STORE_LINK = "https://www.lovescope.app";
export const SHARE_FOOTER_TEXT = "Generated by Lovescope App";
export const SHARE_PREFILLED_TEXT = "Generated with Lovescope";

export const DEFAULT_TIMEZONE = "America/New_York";

// Analyzer screen constants
export const ANALYZER_MAX_IMAGES = 10;
export const ANALYZER_IMAGE_QUALITY = 0.8;
export const ANALYZER_IMAGE_MAX_DIMENSION = 1024;
export const ANALYZER_SEARCH_DEBOUNCE_MS = 300;
export const ANALYZER_SKELETON_COUNT = 6;
export const ANALYZER_INITIALS_MAX_LENGTH = 2;
export const KEYBOARD_OFFSET_IOS = 50;
export const KEYBOARD_OFFSET_ANDROID = 15;

// Onboarding constants
export const ONBOARDING_BUTTON_ACTION = {
  SKIP: "skip",
  CONTINUE: "continue",
} as const;

export const ONBOARDING_QUESTION_TYPE = {
  TEXT: "text",
  RADIO: "radio",
  CARD_OPTIONS: "card_options",
  MULTISELECT: "multiselect",
  CHECKBOX: "checkbox",
  DROPDOWN: "dropdown",
  RANGE: "range",
  SECTION: "section",
  PILL: "pill",
} as const;

export const ONBOARDING_DIRECTION = {
  NEXT: "next",
  BACK: "back",
} as const;

export const EXCLUSIVE_OPTION_VALUES = ["Prefer not to say", "Don't know"];

export const ONBOARDING_DEFAULT_AGE_MIN = 16;
export const ONBOARDING_DEFAULT_AGE_MAX = 60;
export const ONBOARDING_QUESTION_RESET_THRESHOLD = 4;
export const ONBOARDING_ANIMATION_TRANSLATE = 12;
export const ONBOARDING_ANIMATION_DURATION = 180;

// Profile creation steps in onboarding (page_order values)
export const PROFILE_CREATION_START_PAGE_ORDER = 3;
export const PROFILE_CREATION_END_PAGE_ORDER = 6;

// Navigation route names
export const NAV_ROUTES = {
  MAIN_STACK: "MainStack",
  SETTINGS_MAIN: "SettingsMain",
  SET_PREFERENCES: "SetPreferences",
} as const;

// Notifications constants
export const NOTIFICATIONS_PAGE_SIZE = 10;

export const VERIFICATION_VIA = {
  EMAIL: "email",
  PHONE: "phone",
  PHONE_NUMBER: "phone_number",
};

export const PLANS = {
  PREMIUM: "premium",
  PREMIUM_PLUS: "premium_plus",
};

export const CDN_IMAGE_URL = config.cdn_image_url;

export const ANALYZER_ERROR_TEXT_MAX_LENGTH = 2400;
// Country-specific phone number length validation
// Format: countryCode: { minLength, maxLength, pattern }
export const PHONE_VALIDATION_RULES = {
  US: { minLength: 10, maxLength: 10, pattern: /^[0-9]{10}$/ },
  GB: { minLength: 10, maxLength: 11, pattern: /^[0-9]{10,11}$/ },
  CA: { minLength: 10, maxLength: 10, pattern: /^[0-9]{10}$/ },
  NZ: { minLength: 8, maxLength: 10, pattern: /^[0-9]{8,10}$/ },
  AU: { minLength: 9, maxLength: 10, pattern: /^[0-9]{9,10}$/ },
  IE: { minLength: 9, maxLength: 10, pattern: /^[0-9]{9,10}$/ },
  IN: { minLength: 10, maxLength: 10, pattern: /^[0-9]{10}$/ },
} as const;

// Default phone validation rules for unsupported countries
export const DEFAULT_PHONE_VALIDATION = {
  minLength: 7,
  maxLength: 15,
  pattern: /^[0-9]{7,15}$/,
};
