// import { LinearGradient } from './../../node_modules/react-native-linear-gradient/index.d';
export default {
  EYE_CLOSE: require("../assets/images/eye-close-icon.png"),
  EYE_OPEN: require("../assets/images/eye-icon.png"),
  CHECK_ICON: require("../assets/images/check-icon.png"),
  GOOGLE_ICON: require("../assets/images/google-icon.png"),
  APPLE_ICON: require("../assets/images/apple-icon.png"),
  AUTH_BG: require("../assets/images/auth-bg.png"),
  BACK_ICON: require("../assets/images/back-arrow.png"),
  BACK_Bold: require("../assets/images/arrow-bold.png"),
  LOGO: require("../assets/images/logo.png"),
  USER_MENU_ICON: require("../assets/images/user-menu-icon.png"),
  CHAT_MENU_ICON: require("../assets/images/chat-menu-icon.png"),
  HEART_MENU_ICON: require("../assets/images/heart-menu-icon.png"),
  FILE_MENU_ICON: require("../assets/images/file-menu-icon.png"),
  SETTING_MENU_ICON: require("../assets/images/setting-menu-icon.png"),
  PLUS_ICON: require("../assets/images/plus-icon.png"),
  // Friends page icons
  FRIENDS_ICON: require("../assets/images/user2-icon.png"),
  GROUPS_ICON: require("../assets/images/user3-icon.png"),
  REQUESTS_ICON: require("../assets/images/add-user.png"),
  TRASH_ICON: require("../assets/images/delete-icon.png"),
  NOTIFICATION_ICON: require("../assets/images/notifaction-icon.png"),
  THREE_DOTS: require("../assets/images/three-dots.png"),
  SEARCH_ICON: require("../assets/images/search-icon.png"),
  ADD_PROFILE: require("../assets/images/add-profile.png"),
  ARROW_DOWN: require("../assets/images/arrow-down.png"),
  MIC_ICON: require("../assets/images/mic-icon.png"), // Placeholder - replace with actual mic icon
  SEND_ICON: require("../assets/images/submit-icon.png"), // Placeholder - replace with actual send icon
  EXIT_ICON: require("../assets/images/exit-icon.png"),
  // Settings page icons
  MY_PROFILE_ICON: require("../assets/images/my-profile-icon.png"),
  CHANGE_PASSWORD_ICON: require("../assets/images/change-password-icon.png"),
  SUBSCRIPTIONS_ICON: require("../assets/images/subscriptions-icon.png"),
  SET_PREFERENCES_ICON: require("../assets/images/set-preferences-icon.png"),
  LOGOUT_ICON: require("../assets/images/logout-icon.png"),
  ARROW_RIGHT_ICON: require("../assets/images/arrow-right-icon.png"),
  PENCIL_EDIT: require("../assets/images/pencil-edit.png"),
  EDIT_CIRCLE: require("../assets/images/edit-circle.png"),
  BOT_POLYGON: require("../assets/images/bot-polygon.png"),
  USER_POLYGON: require("../assets/images/user-polygon.png"),
  TIMELINE_ICON: require("../assets/images/timeline-icon.png"),
  NO_USER_IMAGE: require("../assets/images/no_user_image.png"),
  LOVE_SEARCH: require("../assets/images/love-search.png"),
  MENU_ICON: require("../assets/images/menu-icon.png"),
  HOME_CHAT_BG: require("../assets/images/home-chat-bg.png"),
  ADD_CHAT_ICON: require("../assets/images/add-chat-icon.png"),
  HISTORY_MENU_ICON: require("../assets/images/history-chat-icon.png"),
  TEXT_ANALYSIS: require("../assets/images/text-analysis.png"),
  TEXT_ANALYSIS_BLUE: require("../assets/images/text-analysis-icon.png"),
  TEXT_ANALYSIS1: require("../assets/images/text-analysis1.png"),
  PARTNER_PORTRAIT: require("../assets/images/partner-portrait.png"),
  PARTNER_PORTRAIT_BLUE: require("../assets/images/user-writer-icon.png"),
  IMAGE_UPLOAD: require("../assets/images/image-upload.png"),
  CLOSE_ICON: require("../assets/images/close-icon.png"),
  CLOSE_ICON2: require("../assets/images/close-black.png"),
  REQUEST_ACCEPT: require("../assets/images/request-accept.png"),
  REQUEST_CANCEL: require("../assets/images/request-cancel.png"),
  // Quiz icons
  QUIZ_USER: require("../assets/images/quiz-user.png"),
  QUIZ_QUESTION: require("../assets/images/quiz-question.png"),
  RESPONSE_BG: require("../assets/images/responsecard-bg.png"),
  LINEARGRADIENT_BG2: require("../assets/images/secondary-cardbg.png"),
  PAYWALL_CARDBG: require("../assets/images/paywall-cardbg.png"),
  // Timeline images
  TIMELINE_MAIN_LINE: require("../assets/images/main-line.png"),
  TIMELINE_LEFT_LINE: require("../assets/images/left-line.png"),
  TIMELINE_RIGHT_LINE: require("../assets/images/rigth-line.png"),
  ADD_PEOPLE_ICON: require("../assets/images/add-people-icon.png"),
  DASH_BORDER: require("../assets/images/dash-border.png"),
  // Analyzer images
  ANALYSIS_ICON: require("../assets/images/analysis-icon.png"),
  ARGUMENT_ANALYSIS_ICON: require("../assets/images/argument-analysis-icon.png"),
  PARTNER_PERSONA: require("../assets/images/partner-persona.png"),
  INTO_YOU: require("../assets/images/into-you.png"),
  SUMMARY: require("../assets/images/summary.png"),
  DETECTED_EMOTION: require("../assets/images/detected-emotions.png"),
  TONE: require("../assets/images/tone.png"),
  SPECIFIED_ANALYSIS: require("../assets/images/specified-analysis.png"),
  SUGGESTED_REPLY: require("../assets/images/suggested-reply.png"),
  PREDICTION: require("../assets/images/predictions.png"),
  WHAT_TO_WATCH_OUT: require("../assets/images/what-to-watch-out.png"),
  RECOMMENDATION: require("../assets/images/recommendations.png"),
  BEHAVIORAL_PATTERN: require("../assets/images/detected-behavioral-pattern.png"),
  COMMUNICATION_STYLE: require("../assets/images/detected-communication-style.png"),
  CONSISTENCY_EFFORT: require("../assets/images/consistency-and-effort.png"),
  TRUST_CREDIBILITY: require("../assets/images/trust-credibility.png"),
  EMOTIONAL_AVAILABILITY: require("../assets/images/emotional-availability.png"),
  KEY_INSIGHTS: require("../assets/images/key-insights.png"),
  RED_FLAG_ICON: require("../assets/images/red-flag-icon.png"),
  GREEN_FLAG_ICON: require("../assets/images/green-flag-icon.png"),
  KEY_MOMENTS: require("../assets/images/key-moments-icon.png"),
  CONFLICT_ICON: require("../assets/images/conflict-pattern-icon.png"),
  INCREASED_ICON: require("../assets/images/increased-icon.png"),
  DECREASED_ICON: require("../assets/images/decreased-icon.png"),
  STABLE_ICON: require("../assets/images/stable-icon.png"),
  ACCOUNTABILITY_ICON: require("../assets/images/accountability-breakdown.png"),
  EMOTIONAL_MATURITY_ICON: require("../assets/images/emotional-maturity.png"),
  ETHICAL_RESPONSIBILITY_ICON: require("../assets/images/ethical-responsibility.png"),
  HIDDEN_MEANING_ICON: require("../assets/images/hidden-meaning.png"),
  FINAL_SUMMARY_ICON: require("../assets/images/final-summary.png"),
  // Onboarding images
  ONBOARDING1: require("../assets/images/onboarding1.png"),
  SHAKE_HAND: require("../assets/images/shake-hand.png"),
  SECURE_ICON: require("../assets/images/secure.png"),

  SHARE_ICON: require("../assets/images/share.png"),
  TOP_RIGHT_GRADIENT: require("../assets/images/top-right-gradient.png"),
  ADD_FRIEND_ICON: require("../assets/images/add-friend-icon.png"),
  MESSAGE_ICON: require("../assets/images/message-icon.png"),
  CALL_ICON: require("../assets/images/calling-icon.png"),
  SUMMARY_ICON: require("../assets/images/summary-icon.png"),
  COMING_SOON_ICON: require("../assets/images/coming-soon-icon.png"),

  UNLOCK_PARTNER_PORTAIT: require("../assets/images/unlock-partner-portrait.png"),
  UNLOCK_ARGUMENT_ANALYSIS: require("../assets/images/unlock-argument-analysis.png"),
  UNLOCK_TEXT_ANALYSIS: require("../assets/images/unlock-text-analysis.png"),
  LOCK_ICON: require("../assets/images/lock-icon.png"),
  REPORT_BUG_ICON: require("../assets/images/report-bug-icon.png"),
  // Subscription plan icons
  FREE_ICON: require("../assets/images/free-icon.png"),
  PREMIUM_ICON: require("../assets/images/premium-icon.png"),
  PREMIUM_PLUS_ICON: require("../assets/images/premium-plus-icon.png"),
};

